# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_size', models.CharField(max_length=200)),
                ('dress_color', models.CharField(max_length=200)),
                ('dress_price', models.CharField(max_length=200)),
                ('dress_title', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dress.Cloth'),
        ),
    ]
